version: "2"
services:
  web:
    build: .
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"