version: "2"
services:
  web:
    build: .
    image: gowiki:latest
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - .:/go/src/app
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"
volumes:
  mongo: {}